name: Deploy to Remote Server

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    # Запускаем job, если событие – push или закрытый (merged) pull_request
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/triens_backend/
            git pull
            docker compose up --build -d
            docker image prune -f
